SELECT
    name AS oid,
	name AS `oid-2`,
    name AS rolname,
    1 AS rolinherit,
    0 AS rolcreaterole,
    0 AS rolcreatedb,
    0 AS rolcanlogin,
    0 AS rolreplication,
    -1 AS rolconnlimit,
    '' AS rolpassword,
    0 AS rolvaliduntil,
    0 AS rolbypassrls,
    array() AS rolconfig,
    0 AS rolsuper,
    0 AS rolcatupdate,
    '' AS description,
    array() AS rolmembership,
    array() AS seclabels,
   'role' as login_type,
    '' AS storage,
    NULL AS auth_type,
    NULL AS auth_params,
    array() AS host_ip,
    array() as host,
    array() AS host_names,
    array() AS host_names_regexp,
    array() AS host_names_like,
    0 AS default_roles_all,
    array() AS default_roles_list,
    array() AS default_roles_except
FROM system.roles
{% if rid %} WHERE name = '{{ rid }}' {% endif %}
