SELECT
    NULL AS attacl,
    0 AS attlen,
    0 AS attndims,
    0 AS attnotnull,
    position AS attnum,
    NULL AS attoptions,
    -1 AS attstattarget,
    'p' AS attstorage,
    0 AS atttypid,
    -1 AS atttypmod,
    type AS cltype,
    type ,
    '' AS collspcname,
    'p' AS defaultstorage,
    NULL AS defval,
    name AS displaytypname,
    23 AS elemoid,
    is_in_sorting_key AS indkey,
    0 AS is_fk,
    0 AS is_sys_column,
    0 AS isdup,
    name,
    NULL AS seclabels,
    name AS typname,
    'public' AS typnspname,
    database,
    table,
    default_kind,
    default_expression,
    data_compressed_bytes,
    data_uncompressed_bytes,
    marks_bytes,
    comment as description,
    is_in_partition_key,
    is_in_primary_key,
    is_in_sampling_key,
    compression_codec
FROM system.columns
WHERE database = '{{ did }}' AND table = '{{ tid }}'
{% if clid %}
 AND name = '{{ clid }}'
{% endif %}
