SELECT
    NULL AS autovacuum_analyze_scale_factor,
    NULL AS autovacuum_analyze_threshold,
    NULL AS autovacuum_enabled,
    NULL AS autovacuum_freeze_max_age,
    NULL AS autovacuum_freeze_min_age,
    NULL AS autovacuum_freeze_table_age,
    NULL AS autovacuum_vacuum_cost_delay,
    NULL AS autovacuum_vacuum_cost_limit,
    NULL AS autovacuum_vacuum_scale_factor,
    NULL AS autovacuum_vacuum_threshold,
    '' AS coll_inherits,
    NULL AS conkey,
    NULL AS conname,
    NULL AS description,
    NULL AS fillfactor,
    0 AS hastoasttable,
    '0' AS inherited_tables_cnt,
    0 AS is_sys_table,
    0 AS isrepl,
    replica_num AS name,
    replica_num AS oid,
    NULL AS relacl_str,
    0 AS relhasoids,
    0 AS relhassubclass,
    0 AS reloftype,
    NULL AS reloptions,
    'default' AS relowner,
    0 AS relpersistence,
    '0' AS reltuples,
    'public' AS schema,
    NULL AS seclabels,
    'public' AS spcname,
    0 AS spcoid,
    NULL AS toast_autovacuum_analyze_scale_factor,
    NULL AS toast_autovacuum_analyze_threshold,
    NULL AS toast_autovacuum_enabled,
    NULL AS toast_autovacuum_freeze_max_age,
    NULL AS toast_autovacuum_freeze_min_age,
    NULL AS toast_autovacuum_freeze_table_age,
    NULL AS toast_autovacuum_vacuum_cost_delay,
    NULL AS toast_autovacuum_vacuum_cost_limit,
    NULL AS toast_autovacuum_vacuum_scale_factor,
    NULL AS toast_autovacuum_vacuum_threshold,
    NULL AS toast_reloptions,
    '0' AS triggercount,
    NULL AS typname,
    NULL AS typoid,
    cluster,
    shard_num,
    shard_weight,
    replica_num,
    host_name,
    host_address,
    port,
    is_local,
    user,
    default_database,
    errors_count,
    estimated_recovery_time
FROM
   system.clusters
WHERE
    cluster = '{{ did }}' 
    {% if scid %} AND shard_num = {{ scid }} {% endif %}
    {% if tid %} AND replica_num = {{ tid }} {% endif %}